{% set name = "Flask-Creole" %}
{% set version = "0.4.4" %}
{% set compress_type = "tar.gz" %}
{% set sha256 = "af308ba55fdda617d715877d74cdedea75727669e0555ef2a09539220318622d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  skip: True  # [py3k]
  number: 1000
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask
    - creoleparser

test:
  imports:
    - flaskext
    - flaskext.creole

about:
  home: http://bitbucket.org/aafshar/flask-creole-main
  license: MIT
  # license_file: No LICENSE in MANIFEST.in - see https://bitbucket.org/aafshar/flask-creole-main/pull-requests/1/
  license_family: MIT
  summary: 'Creole parser filters for Flask'
  doc_url: https://pythonhosted.org/Flask-Creole/
  dev_url: http://bitbucket.org/aafshar/flask-creole-main

extra:
  recipe-maintainers:
    - pmlandwehr
