travis:
  secure:
    BINSTAR_TOKEN: LeHKthnfkoiztWyok8G34g5DHaQ6YvMKwas4HOuSBI+ArqkZs3W4VDVJycBQad5gzZlzMCIzj1wPDaUSGGe5dfCAWg1O+lYn3AVMmCsAmIITBC0ZbhY+yt31Qcm4CC1B46v69V8/DsETzl2SSTOfmAWBh9pfeYuiKO18DuStbg6Hc/BwYtzOjd4vRbNvpHQzVd47CblQw89+sfN7nXczo4JbLi4tM9O0Kn5VGU/zTbBH/oM71JvuTIQsvzeS05ntN1Y24BGLhBOPbPBdcmnMxzij1YaT6BpUrTRbe303NigTjOX9TxIcGMfKxdO7jWn8CbnjAq2qYpZUtNfm9EtH5g2upX2L8TV4OlbNFKtrdbKtynDElZFZJq4tIII5p8KbDVcDhw5/q5J0GXOzaO6J7tC3i+qC4y30+G19B3sqofOipD0Q6T8RsFtG3IlRRdZnOFn13s7RPwtigR4g3LMlL6Yv9DKylRaIn3RDveT8nEm4mqLfFnQB8OEQhvtIeE7TKCWH04h5eXh580xPwC/p9z+NpoYUcz61PXymileOg5p6GbB09P7fQKPTUeVFPC/GO4NrCr0qkvqM8yZ97r6r2aGeh3pO+c2bhSjkBuHiEdXejmSdajKs1KtcjPndcSCv9BjIC5bPMIQVuVgwy1fht3dG8fsBbFneY5fUaqb7hJo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
