travis:
  secure:
    BINSTAR_TOKEN: FIC5D7+DSg+8gsT+c5y/7nGVK1i+USmhv7fJ5XNf7XsvC9qzKwmQ4XPr7zX9ixhLWin9XiTcEoxx0Bn4afZ0ZqS+mElAZC6pa8um5KwuzRebfVYScSnB4ceWcneg3vjMMVmi4VDgDLrAB440tJW+eXv6JaJbNXBU9LMTzKjmY3sm43XXfx6twRYSs+ZuDA6qwlJu+1B8qcOVBnvC+X5402go9gk1Apvk/vB6hXtGwvhaUKv9OFW63xwUFcGvQGCkcVwwT3SW3Eownh6gwKaaHe1L8Px5aEdll8ebJ3+I3RgZnt8wzSm3SV+Z1bEJ+k6Cl+bwBfonp+gmGFe0fU0TLeZ6yjZZdU9vmDc6IZyJMoHLee7xPFKMTGV+EDPQxOW4vetX7BREpFArgl9K4GNjthfVfSrjwMrAH4PwuptUNFIuBHB8pBdAIjhqYkrNu0xMIV7eaoEKnWSlL5po8zztz3xzMyFakdFOqI7YxQtBL35oMiboiZIaUuuGTrOzrF5isfIfxZgYsjoXMQFOz0Ofoq0lI90auoGSPsrdblrfjicV387uiI+RcctmyOuYv9woz9Po4fe7kR7M9iKxz9FFiJNbLG4H9/tK1TlBhm6rusWNdaRd/EsWGMu/ocM/MWxnDfsB00hfv6k84AbUiEj+50ztZicbINqjclu5ljsLYLc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
